### ISSUE TITLE
404 not found blog posts (Vercel Deployment)

### ISSUE THREAD

**Issue by Logenleedev** [DavideBri/Gesko#23]
I cloned this template and used it for my blog. After I wrote a test article, I pushed it to vercel. However, seems like every time I click the blog post, it shows 404 page.

Currently, the blog post's URL is "https://xxxxxx-blog.vercel.app/2022/06/07/opening-message". Not sure which part I did wrong. Do I need to change the setting in _config.yml ?

**Comment by P0WEX** [comment]
Thanks for adding new info,
Unfortunately my experience with Vercel deployment is very poor, but I will investigate on this when I can.

In the meanwhile, if you discover something that fix this, update this Issue so everybody can benefit from this.
