### ISSUE TITLE
New features proposal

### ISSUE THREAD

**Issue by andreabusi** [DavideBri/Gesko#26]
Hi!
I'm working on some features for the theme. I want to share some changes that I made for my blog to discuss if could be useful also for the Gesko theme. Here is the list:

1. Add `comments-enable` option to enable/disable Disqus comments. If false, the comments section is no longer visible
2. Add more social channels (Linkedin, Mastodon) and show them in the `social footer` only if they are configured in the `_config.yml` file
3. Migrate to FontAwesome v6.0 (to have some new icons, like the Mastodon one). This could be quite tricky because every user has to create a new Kit on the FontAwesome site

Could be these features interesting for the theme? If yes, I can create the PRs.

**Comment by DavideBri** [comment]
Sounds good! Sure make a PR! I'd love to make Gesko up to date!

**Comment by andreabusi** [comment]
[PR](https://github.com/DavideBri/Gesko/pull/27) created with the proposed changes. Let me know :)
