### ISSUE TITLE
Upgrade Ruby Version

### ISSUE THREAD

**Issue by eerFun** [DavideBri/Gesko#28]
Hi there,
Recently, I switched to a new machine and wanted to prepare my system for running this project. I found that ruby `2.7.2` was too old and no longer supported.
I think it's better to upgrade ruby version of the project to `3.x.x` if possible.

**Comment by DavideBri** [comment]
thanks eerFun for pointing that out!

I just enable Dependabot to help keep the version updated. If that will not do the work I'll do it in the next days.

D

**Comment by DavideBri** [comment]
https://github.com/DavideBri/Gesko/commit/0b3397605f1328e7c9d09b567c2ee0c85d21ac83

**Comment by eerFun** [comment]
That's great @DavideBri. Thank you!
